# Schema for the configuration files of the Mix module.
mix.settings:
  type: config_object
  label: 'Mix settings'
  mapping:
    hide_revision_field:
      type: boolean
      label: 'Hide revision field'
    dev_mode:
      type: boolean
      label: 'Enable development mode'
    remove_x_generator:
      type: boolean
      label: 'Remove X-Generator'
    register_password:
      type: boolean
      label: 'Register password'
    error_page:
      type: mapping
      label: 'Error page settings'
      mapping:
        mode:
          type: boolean
          label: 'Enable custom error page'
        content:
          type: string
          label: 'Error page content'
    config_import_ignore:
      type: mapping
      label: 'Config import ignore'
      mapping:
        mode:
          type: boolean
          label: 'Enable config import ignore'
        list:
          type: sequence
          label: 'Ignored config names'
          sequence:
            type: string

block.block.*.third_party.mix:
  type: mapping
  label: Block third party settings
  mapping:
    class:
      type: string
      label: Block class(es)
    dropdown:
      type: boolean
      label: Dropdown
